### ISSUE TITLE
Appium-Python-Client 1.0.0 breaks robotframework-appiumlibrary in Python3

### ISSUE THREAD

**Issue by robco** [serhatbolsu/robotframework-appiumlibrary#286]
Steps to reproduce:
1. Install robotframework-appiumlibrary 1.5.0.4 (latest)
=> Appium-Python-Client 1.0.0 dependency (released on 16th May 2020) installed automatically
2. In python try to import AppiumLibrary
=> ModuleNotFoundError: No module named 'appium.webdriver.common'

Full stacktrace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/AppiumLibrary/__init__.py", line 4, in <module>
    from AppiumLibrary.keywords import *
  File "/usr/local/lib/python3.7/dist-packages/AppiumLibrary/keywords/__init__.py", line 9, in <module>
    from ._touch import _TouchKeywords
  File "/usr/local/lib/python3.7/dist-packages/AppiumLibrary/keywords/_touch.py", line 3, in <module>
    from appium.webdriver.common.touch_action import TouchAction
ModuleNotFoundError: No module named 'appium.webdriver.common'

**Comment by robco** [comment]
Appium-Python-Client [1.0.1](https://github.com/appium/python-client/releases/tag/v1.0.1) fixed this issue. Closing
