### ISSUE TITLE
getting Error "ModuleNotFoundError: No module named 'appium.webdriver.common.touch_action' " during launch application

### ISSUE THREAD

**Issue by Suphakorn95** [serhatbolsu/robotframework-appiumlibrary#424]
Hello All, I'm facing error below
"**Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'appium.webdriver.common.touch_action'** "

I am using:

- python version: 3.12.0

- appium 2.5.1

- robotframework: 7.0.0

- robotframework-appiumlibrary: 2.0.0

Please see error details below;

(.venv) MBPkhxngPaytine:mobile-automatate suphakorn$ robot -d Output --loglevel TRACE Tests/Login.robot
[ ERROR ] Error in file '/Users/suphakorn/PycharmProjects/mobile-automatate/Resources/Import.robot' on line 2: Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'appium.webdriver.common.touch_action'
Traceback (most recent call last):
  File "/Users/suphakorn/PycharmProjects/mobile-automatate/.venv/lib/python3.12/site-packages/AppiumLibrary/__init__.py", line 4, in <module>
    from AppiumLibrary.keywords import *
  File "/Users/suphakorn/PycharmProjects/mobile-automatate/.venv/lib/python3.12/site-packages/AppiumLibrary/keywords/__init__.py", line 9, in <module>
    from ._touch import _TouchKeywords
  File "/Users/suphakorn/PycharmProjects/mobile-automatate/.venv/lib/python3.12/site-packages/AppiumLibrary/keywords/_touch.py", line 3, in <module>
    from appium.webdriver.common.touch_action import TouchAction
PYTHONPATH:
  /Users/suphakorn/PycharmProjects/mobile-automatate/.venv/bin
  /Library/Frameworks/Python.framework/Versions/3.12/lib/python312.zip
  /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12
  /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload
  /Users/suphakorn/PycharmProjects/mobile-automatate/.venv/lib/python3.12/site-packages
  
  

  Please help me. Thanks you in advance.

**Comment by ajaxpp** [comment]
try use this command 
$ pip install --force-reinstall "Appium-Python-Client<4.0.0"
[https://stackoverflow.com/questions/78310223/modulenotfounderror-no-module-named-appium-webdriver-common-touch-action](url)

**Comment by rasjani** [comment]
dupe; https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/417 and suggested fix https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/418
