### ISSUE TITLE
Session Not Created Due to Invalid 'disableIdLocatorAutocompletion' Setting Value Type

### ISSUE THREAD

**Issue by devmrcs** [serhatbolsu/robotframework-appiumlibrary#432]
## Description:

We encountered an issue where a new session could not be created due to an invalid type for the 'disableIdLocatorAutocompletion' setting. The error message indicates that a java.lang.String was provided, but a java.lang.Boolean was expected.

## Environment:

OS: MacOS 14.1 (23B2073)
Appium version: 2.11.1
Appium UIAutomator2 Driver version: 3.1.0

Appium-Python-Client==3.2.1
robotframework==7.0
robotframework-appiumlibrary==2.1.0
selenium==4.12.0

## Steps to Reproduce:

Attempt to create a new session with the following setting:

```
    Open Application    http://127.0.0.1:4723
    ...    disableIdLocatorAutocompletion=true
   
```

## Expected Behavior:
The session should be created successfully when a valid boolean value is provided for the 'disableIdLocatorAutocompletion' setting.

## Actual Behavior:

Observe the error message indicating the type mismatch.

The session creation fails with the following stacktrace:

```
SessionNotCreatedException: Message: A new session could not be created. Details: io.appium.uiautomator2.common.exceptions.InvalidArgumentException: Invalid 'disableIdLocatorAutocompletion' setting value type. Got: java.lang.String. Expected: java.lang.Boolean.
Stacktrace:
io.appium.uiautomator2.common.exceptions.SessionNotCreatedException: io.appium.uiautomator2.common.exceptions.InvalidArgumentException: Invalid 'disableIdLocatorAutocompletion' setting value type. Got: java.lang.String. Expected: java.lang.Boolean.
        at io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:60)
        at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)
        at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:259)
        at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:253)
        at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:77)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:920)
Caused by: io.appium.uiautomator2.common.exceptions.InvalidArgumentException: Invalid 'disableIdLocatorAutocompletion' setting value type. Got: java.lang.String. Expected: java.lang.Boolean.
        at io.appium.uiautomator2.model.settings.AbstractSetting.convertValue(AbstractSetting.java:82)
        at io.appium.uiautomator2.model.settings.AbstractSetting.update(AbstractSetting.java:36)
        at io.appium.uiautomator2.model.Session.<init>(Session.java:47)
        at io.appium.uiautomator2.model.AppiumUIA2Driver.initializeSession(AppiumUIA2Driver.java:42)
        at io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:53)
        ... 34 more
```

**Comment by devmrcs** [comment]
To correctly set the disableIdLocatorAutocompletion parameter, ensure you pass the value within curly brackets to denote it as a boolean:

```diff
    Open Application    http://127.0.0.1:4723
-    ...    disableIdLocatorAutocompletion=true    
+    ...    disableIdLocatorAutocompletion=${True}
```

This change ensures that the value is interpreted correctly as a boolean True instead of a string "true". This resolves issues related to incorrect value type being passed, which can cause errors during session creation.
